export enum Estado {
    PENDIENTE = "PENDIENTE",
    PREPARACION = "PREPARACION",
    LISTO_PARA_ENTREGA = "LISTO_PARA_ENTREGA",
    EN_DELIVERY = "EN_DELIVERY",
    CANCELADO = "CANCELADO",
    RECHAZADO = "RECHAZADO",
    ENTREGADO = "ENTREGADO",
    FACTURADO = "FACTURADO",
}